### PR TITLE
Revert "Create testPulls.txt"

### PR DESCRIPTION
**Pull request by ryanmichaelcurry**
Reverts ryanmichaelcurry/group1#7

### CODE REVIEW

**Review by rayhanamin118 — APPROVED** [review]
looks good!

**Review by hutdude — APPROVED** [review]
Looks good

**Review by will-cozart — APPROVED** [review]
I approve

**Review by HunterMMoore — APPROVED** [review]
Looks good

**Comment by ryanmichaelcurry** [comment]
pull request was approved by all members in the group

**Pull request closed without merging**
